<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>notaverse_threejs_test1</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
	  <Content Include="wwwroot\**\*">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="notaverse-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.JSInterop" Version="10.0.12" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\notaverse-logo.png" />
  </ItemGroup>

</Project>
